### ISSUE TITLE
Virus warnings

### ISSUE THREAD

**Issue by snuped** [wladradchenko/wunjo.wladradchenko.ru#39]
Hello,

A few of your models you have links to in the json files are scanning as severe viruses:

1. "mapping_00229-model.pth.tar": "https://github.com/Winfredy/SadTalker/releases/download/v0.0.2/mapping_00229-model.pth.tar",
2. "facevid2vid_00189-model.pth.tar": "https://github.com/Winfredy/SadTalker/releases/download/v0.0.2/facevid2vid_00189-model.pth.tar",

Windows is suggesting that these are both infected with Trojan:Win32/Sirefef!cfg. Both are associated with the SadTalker program. 

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FSirefef!cfg&threatid=170766

Can you explain?

**Comment by wladradchenko** [comment]
Hello. 

You can see by links what those are SadTalker models from them repository, and all issue questions about SadTalker models, you need to open in them repository.

However, antiviruses can make mistakes, if you can confirm that there is indeed a virus, and not a bug of one specific antivirus, let me know so that I can remove this module from the program.
