### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by snuped** [wladradchenko/wunjo.wladradchenko.ru#41]
Hello,

When I try to run app.py from Visual Studio I get the errors:

C:\Users\test\.wunjo\deepfake\custom_diffusion.json already exists!
C:\Users\test\.wunjo\user_trained_voice\INSTRUCTION.md already exists!
C:\Users\test\.wunjo\user_trained_voice\custom_user.json already exists!
Press any key to continue . . .

The app never starts. Can I run this from Visual Studio?

Thanks!

**Comment by wladradchenko** [comment]
Hello. You can run only using briefcase command, to launch outside the briefcase, all library imports would have to be rewritten.

**Comment by Kedreamix** [comment]
Could you please specify where exactly I should initiate the startup process? Additionally, is there a specific command or method to use, such as the briefcase command mentioned in the comments?

**Comment by Kedreamix** [comment]
When I use the command `briefcase dev` via SSH, it seems that no window is appearing. How can I resolve this issue?

**Comment by wladradchenko** [comment]
> When I use the command `briefcase dev` via SSH, it seems that no window is appearing. How can I resolve this issue?

Hello. Yes, you will not see any windows because inside using FlaskUI witch run random free port and browser. Firstly you need to in [app.py](https://github.com/wladradchenko/wunjo.wladradchenko.ru/blob/main/portable/src/wunjo/app.py) set DEBUG True (47 line) to use as flask app by ip:port or remove lines from 1341 to 1349. Secondly in app.run you need to set localhost as 0.0.0.0. 

After you can setting your machine for your specific open port to access via internet, ip, using Nginx, Gunicorn, etc.

**Comment by Kedreamix** [comment]
Thank you for your guidance! Issue resolved successfully.
