### ISSUE TITLE
Voice clonning doesn't work in Firefox

### ISSUE THREAD

**Issue by mrsndmn** [wladradchenko/wunjo.wladradchenko.ru#45]
But it works in Chrome, thank you)
If fix is non-trivial, I could propose to add warning for Firefox users

## Environment

* Macos Sonoma 14.2.1 (23C71)
* Python 3.10.13
* Firefox 121.0.1
* wunjo.wladradchenko.ru commit 3d4f43fec6a04081311555516fb33059a8bc32a7

## Steps to reproduce:

1. Run app
```
DEBUG=1 PYTHONPATH=. ~/miniconda3/envs/wunjo/bin/briefcase dev
```
2. Go to "Voices configuration panel"
3. Choose local file
4. Click on Recognize text

**Actual result:**

Nothing happen, stack trace in browser console
```
Uncaught (in promise) ReferenceError: can't access lexical declaration 'translationsCache' before initialization
    translateWithGoogle http://localhost:8000/static/basic/js/index.js:1256
    submittedSTT http://localhost:8000/static/basic/js/index.js:402
    settingTextToSpeech http://localhost:8000/static/basic/js/index.js:549
    settingTextToSpeech http://localhost:8000/static/basic/js/index.js:548
    onclick http://localhost:8000/:1
```
https://github.com/wladradchenko/wunjo.wladradchenko.ru/blob/main/portable/src/wunjo/static/basic/js/index.js#L1254

**Expected result:**

Process of speaker embedding is started

**Comment by wladradchenko** [comment]
Hello. Do you mean what doesn't work great Google Text Recognition in Firefox? Because I don't understand how this can be relate to Voice Cloning, because process of Voice Cloning in backend. If you mean Google Text Recognition, I will show on this trouble in next update. Maybe I will find solution to use backend Text Recognition without Google. Now I can use backend neural networks from transformers because of specific version for Video2Video and need ro think how install 2 difference versions of transformers in venv.

**Comment by wladradchenko** [comment]
Solved
