### ISSUE TITLE
REQ: Add French language

### ISSUE THREAD

**Issue by benbois** [wladradchenko/wunjo.wladradchenko.ru#53]
Hi, 
Excellent work, thanks for that!

Is it possible to add French language on wunjo AI?

**Comment by wladradchenko** [comment]
Hello.  The upcoming update v2.0 will only include improvements to video without features for audio.  In the next update v2.1. I will completely change the approach to speech synthesis and cloning so that many popular languages can be supported.  The current approach is not very good and adding new languages is difficult.
