### ISSUE TITLE
notthing show up when install ver 2.0.3 on window 11

### ISSUE THREAD

**Issue by KalvinThien** [wladradchenko/wunjo.wladradchenko.ru#63]
![image](https://github.com/user-attachments/assets/75caeaa1-57a1-4d6e-9476-9c475ea2ce21)

**Comment by wladradchenko** [comment]
Hello,

We need more information to better understand the issue. Essentially, Wunjo is a Flask application, and when you open it from the Start menu, it runs by default on 127.0.0.1:8000 (you can enter this in any browser, and it will open). The default browser for it is [webgui](https://github.com/wladradchenko/webgui.wladradchenko.ru). However, you can configure it to open in any other browser.

To do this, go to the file [app.py](https://github.com/wladradchenko/wunjo.wladradchenko.ru/blob/main/portable/src/wunjo/app.py) and modify the line FlaskUI(server=server, browser_path=WEBGUI_PATH, server_kwargs={"app": app, "port": port}).run(). Instead of WEBGUI_PATH, set it to None or the path to any other browser.

From the screenshot, it appears that you might be opening only the webgui and not the application itself, which is why you're seeing a black screen.

**Comment by KalvinThien** [comment]
Tôi đã chạy nó bằng bản càu đặt exe

Vào Th 4, 31 thg 7, 2024 lúc 12:04 Wladislav Radchenko <
***@***.***> đã viết:
