### ISSUE TITLE
briefcase build uses system python version

### ISSUE THREAD

**Issue by brcisna** [wladradchenko/wunjo.wladradchenko.ru#67]
Debian linux 13 'Trixie'

wunjo installed into a venv of python-3.10.12  and activated
when i try and do a briefcase build the build errors immeditely 

"The version of Python being used to run Briefcase (3.10) is not the system python3 (3.12)."

Am on a new Linux build for a powerful CPU,,,and decent GPU.
Almost certain i got a succesful briefcase build a couple weeks ago,,on Debian 12 

Ideas?

Thanks

**Comment by wladradchenko** [comment]
As I understand it, this problem is related to Zluda, judging by other open topics. Maybe you build zluda for system python 3.12, but run app with pyhon3.10, because python 3.12 not supported some libs. Based on the description, it is not clear what the error is related to ZLUDA and what caused it.

I think there is no need to open new issue topics separately from the [question](https://github.com/wladradchenko/wunjo.wladradchenko.ru/issues/65) or additional [issue](https://github.com/wladradchenko/wunjo.wladradchenko.ru/issues/68), if they are interconnected, it will be more difficult for users to navigate.
