### ISSUE TITLE
"I encountered a failure when installing software on Windows. The log is as follows:

### ISSUE THREAD

**Issue by wxc1207** [wladradchenko/wunjo.wladradchenko.ru#70]
[Errno 13] Permission denied: 'C:\\Program Files\\Wladislav Radchenko\\Wunjo\\app_packages\\functorch\\_C.cp310-win_amd64.pyd'

**Comment by wladradchenko** [comment]
Hi. You have installed Wunjo for admin root, but open by user root, this reason why you get permission not found, because user bot have permissions to download torch in folder created admin. You have 2 way:

1) Reinstall Wunjo only for current user (not for all).
2) Navigate to the `Wunjo` directory app, open the console, and enter the following command:  `icacls * /grant:r "Users:(R,W)" /T`, where Users this name of user group.
